$(document).ready(function(){$.display={},$.display.pageSpeed=300,$.display.loadingTime=1500,$.display.page={},$.display.switchPage=function(t){$(".page").not(t).css("zIndex",0),$(t).css("zIndex",10),$(t).show();var e=t.split("page")[1].toLowerCase();$.display.page[e].load(),$(".page").not(t).css({left:"-200vw"}).hide(),$(t).css({left:"0"}).show()},$.display.updateCounts=function(){$.db.table("products").where("bin_id").equals(-1).count(function(t){$.inventory.newProducts=t,$(".num-total-new").html(t)}),$.db.table("bins").count(function(t){$.inventory.totalBins=t,$(".num-total-bins").html(t)}),$.db.table("products").count(function(t){$.inventory.totalProducts=t,$(".num-total-products").html(t)})},$.display.updateLastUpdateText=function(){var t=new Date,e="Last Refresh: "+(t.getMonth()+1)+"/"+t.getDate()+"/"+t.getFullYear()+" @ "+t.getHours()+":"+t.getMinutes();$("#lastUpdatedText").html(e)},$.display.toggleLoadingScreen=function(){$("#loadingOverlay").show(),setTimeout(function(){$("#loadingOverlay").fadeOut("slow",function(){$(this).hide()})},$.display.loadingTime)}});

$(document).ready(function(){$.etsy={},$.etsy.apiURL="https://openapi.etsy.com/v2/",$.etsy.apiKey="tpgge44ziiwldztbd8hx7b1r",$.etsy.recentResultsLimit=20,$.etsy.resultLimit=100,$.etsy.storeName="JessicaAnnsEmporium",$.etsy.listingParams={fields:["listing_id","title","category_path","category_id","price","quantity","style","state","taxonomy_id","creation_tsz","original_creation_tsz"]},$.etsy.buildURL=function(t,e,i){i="undefined"!=typeof i?i:$.etsy.resultLimit,e="undefined"!=typeof e?e:0;var s=$.etsy.apiURL+t+"?api_key="+$.etsy.apiKey+"&offset="+e+"&limit="+i+"&",n="";return $.each($.etsy.listingParams,function(t,e){n+=t+"="+e.toString()+"&"}),s+n},$.etsy.getListings=function(t,e,i){e="undefined"!=typeof e?e:0,i="undefined"!=typeof i?i:$.etsy.resultLimit;var s=$.etsy.buildURL("shops/"+$.etsy.storeName+"/listings/active.js",e,i);$.ajax({url:s,dataType:"jsonp",success:function(e){e.ok?t(e.count>0?e:[]):(console.log("API Error: "+e.error),t([]))}})}});

$(document).ready(function(){$.etsyDB={},$.etsyDB.init=function(){Dexie.getDatabaseNames(function(t){-1==t.indexOf("etsyDB")?$.createDB():$.db.open()})},$.etsyDB.create=function(){$.db.version(1).stores({products:"++id, bin_id, listing_id, title, categories, price, created, original_created",bins:"++id, name, notes"}),console.log("Created database"),$.db.open()},$.etsyDB.addListing=function(t){$.db.table("products").where("listing_id").equals(t.listing_id).count(function(e){0===e&&$.db.table("products").add({bin_id:-1,listing_id:t.listing_id,title:t.title,categories:t.category_path.toString(),price:t.price,created:t.creation_tsz,original_creation:t.original_creation_tsz}).then(function(){console.log("Added listing #"+t.listing_id)})})},$.etsyDB.listTables=function(){$.db.tables.forEach(function(t,e){console.log("Table "+e+": "+t.name)})},$.etsyDB.deleteDB=function(){$.db["delete"]().then(function(){console.log("Deleted database")})},$.etsyDB["export"]=function(){return $.db.transaction("r",$.db.tables,function(){function t(){var i=e.shift();return i.toArray().then(function(o){return n.push({tableName:i.name,contents:o}),e.length>0?t():n})}var e=$.db.tables.map(function(t){return Dexie.currentTransaction.tables[t.name]}),n=[];return t()})}});

$(document).ready(function(){$.etsy.refreshRecentListings=function(t){$.each(t.results,function(t,e){$.etsyDB.addListing(e)}),$.display.updateCounts(),$.display.updateLastUpdateText(),Materialize.toast("Successfully updated recent listings",4e3)},$.etsy.refreshAllListings=function(t){$.each(t.results,function(t,e){$.etsyDB.addListing(e)}),null!==t.pagination.next_offset?$.etsy.getListings($.etsy.refreshAllListings,t.pagination.next_offset,$.etsy.resultLimit):($.display.updateCounts(),$.display.updateLastUpdateText(),Materialize.toast("Succesfully updated all listings",4e3))},$.etsy.getNewProducts=function(t){$.db.table("products").where("bin_id").equals(-1).toArray().then(function(e){t(e)})},$.etsy.getAllProducts=function(t){$.db.table("products").toArray().then(function(e){t(e)})},$.etsy.getBins=function(t){$.db.table("bins").toArray().then(function(e){t(e)})}});

$(document).ready(function(){$(".dropdown-button").dropdown(),$(".tooltipped").tooltip({delay:50}),$(".page").not("#pageDashboard").hide().css({left:"-200vw"}),$.db=new Dexie("etsyDB"),$.etsyDB.init(),$.display.page.dashboard.load(),$.inventory={newProducts:0,totalBins:0,totalProducts:0},$(".nav-link").on("click",function(t){t.preventDefault(),$(".nav-link").not($(this)).parent().removeClass("active"),$(this).parent().addClass("active");var e=$(this).attr("href");$.display.toggleLoadingScreen(),$.display.switchPage(e)}),$("#updateRecent").on("click",function(){Materialize.toast("Refreshing recent listings...",4e3),$.etsy.getListings($.etsy.refreshRecentListings,0,$.etsy.recentResultsLimit)}),$("#updateAll").on("click",function(){Materialize.toast("Refreshing all listings...",4e3),$.etsy.getListings($.etsy.refreshAllListings,0,$.etsy.resultLimit)}),$.db.on("ready",function(){})});

$(document).ready(function(){$.display.page.bins={},$.display.page.bins.load=function(){console.log("Loaded bins")}});

$(document).ready(function(){$.display.page.dashboard={},$.display.page.dashboard.load=function(){console.log("Loaded dashboard")}});

$(document).ready(function(){$.display.page.newproducts={},$.display.page.newproducts.load=function(){console.log("Loaded newproducts")}});

$(document).ready(function(){$.display.page.products={};var t=$("#productTemplate").clone();$("#productTemplate").remove(),$.display.page.products.load=function(){$.display.toggleLoadingScreen($.etsy.getAllProducts($.display.page.products.drawProducts)),$.etsy.getAllProducts($.display.page.products.drawProducts)},$.display.page.products.drawProducts=function(e){var r="";$.each(e,function(e,d){var i=t;i.removeClass("template");var a=i.find(".listing-url");a.attr("href","http://www.etsy.com/listing/"+d.listing_id),a.html(d.title),i.find(".bin-id").html(-1==d.bin_id?"None":d.bin_id),i.find(".price").html(d.price);var n=new Date(1e3*d.created);i.find(".created").html(n.toGMTString());var o=new Date(1e3*d.original_creation);i.find(".original-created").html(o.toGMTString()),r+="<tr>"+i.html()+"</tr>"});var d=document.getElementById("productTableBody");d.innerHTML=r}});

//# sourceMappingURL=all.js.map